### ISSUE TITLE
Exception in Affinity Package

### ISSUE THREAD

**Issue by khojes** [OpenHFT/Java-Thread-Affinity#12]
package javaapplication1;
import vanilla.java.affinity.AffinityLock;
/*
import vanilla.java.clock.ClockSupport;
import vanilla.java.clock.IClock;
import java.io.IOException;
import java.util.Random;
*/

public class JavaApplication1 
{
    public static void main(String[] args) 
    {
       AffinityLock al = AffinityLock.acquireLock();
        try {
            new Thread(new SleepRunnable(), "reader").start();
            new Thread(new SleepRunnable(), "writer").start();
            new Thread(new SleepRunnable(), "engine").start();
        } finally {
            al.release();
        }
        System.out.println("\nThe assignment of CPUs is\n" + AffinityLock.dumpLocks());
    }
    private static class SleepRunnable implements Runnable {
        public void run() {
            AffinityLock al = AffinityLock.acquireLock();
            try {
                System.out.println("Hello World...!!");
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            } finally {
                al.release();
            }
        }
    }
}

Hello,

I have Written the above Code.

And got stuck in this Exception : 
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/WinDef$DWORD
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2427)
        at java.lang.Class.privateGetPublicMethods(Class.java:2547)
        at java.lang.Class.getMethods(Class.java:1410)
        at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:409)
        at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:306)
        at java.lang.reflect.Proxy.getProxyClass(Proxy.java:501)
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:581)
        at com.sun.jna.Native.loadLibrary(Native.java:371)
        at com.sun.jna.Native.loadLibrary(Native.java:353)
        at vanilla.java.affinity.impl.WindowsJNAAffinity$CLibrary.<clinit>(WindowsJNAAffinity.java:48)
        at vanilla.java.affinity.impl.WindowsJNAAffinity.getAffinity(WindowsJNAAffinity.java:70)
        at vanilla.java.affinity.impl.WindowsJNAAffinity.<clinit>(WindowsJNAAffinity.java:60)
        at vanilla.java.affinity.AffinitySupport.<clinit>(AffinitySupport.java:42)
        at vanilla.java.affinity.AffinityLock.<clinit>(AffinityLock.java:44)
        at javaapplication1.JavaApplication1.main(JavaApplication1.java:15)
Java Result: 1
BUILD SUCCESSFUL (total time: 0 seconds)

**Comment by vamshigunji183** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package threaddemo;
//import Thread;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package threaddemo;

/**
 *
 * @author gvvam
 */
import net.openhft.affinity.AffinityLock;

public class ThreadDemo1 {
public static void main(String[] ignored) throws InterruptedException {
AffinityLock al = AffinityLock.acquireLock();
try {
new Thread(new SleepRunnable(), "reader").start();
new Thread(new SleepRunnable(), "writer").start();
new Thread(new SleepRunnable(), "engine").start();
} finally {
al.release();
}
// wait for the threads to start.
Thread.sleep(200);
System.out.println("\nOn "+System.getProperty("os.name")+" the assignment of CPUs is\n" + AffinityLock.dumpLocks());
}

private static class SleepRunnable implements Runnable {
    public void run() {
        AffinityLock al = AffinityLock.acquireLock();
        try {
            System.out.println("Hello World...!!");
            Thread.sleep(1000);
        } catch (InterruptedException e) {
        } finally {
            al.release();
        }
    }
}



Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at net.openhft.affinity.AffinityLock.<clinit>(AffinityLock.java:47)
	at threaddemo.ThreadDemo1.main(ThreadDemo1.java:24)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more



this is the error that i am facing.
I have referred to the whole issue but still i could not able to run the program

**Comment by peter-lawrey** [comment]
Have you included the slf4j library? If you use maven it includes it for
you.
ᐧ
