### ISSUE TITLE
If a lock can't be removed, skip the cpu.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Java-Thread-Affinity#130]
```
2024-07-11T14:57:03.439+0100 [main/queue-cluster-1-/replication-event-loop] WARN net.openhft.affinity.LockInventory - Error occurred acquiring lock
java.nio.file.AccessDeniedException: /tmp/cpu-14.lock
  at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
  at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
  at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
  at net.openhft.affinity.lockchecker.FileLockBasedLockChecker.tryAcquireLockOnFile(FileLockBasedLockChecker.java:134)
  at net.openhft.affinity.lockchecker.FileLockBasedLockChecker.obtainLock(FileLockBasedLockChecker.java:107)
  at net.openhft.affinity.LockCheck.storePid(LockCheck.java:74)
  at net.openhft.affinity.LockCheck.replacePid(LockCheck.java:59)
  at net.openhft.affinity.LockCheck.updateCpu(LockCheck.java:97)
  at net.openhft.affinity.LockInventory.updateLockForCurrentThread(LockInventory.java:84)
  at net.openhft.affinity.LockInventory.acquireLock(LockInventory.java:138)
  at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:305)
  at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:189)
  at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:287)
  at net.openhft.chronicle.threads.MediumEventLoop.run(MediumEventLoop.java:253)

```

**Comment by hft-team-city** [comment]
Released in [Java-Thread-Affinity-3.26ea5](https://github.com/OpenHFT/Java-Thread-Affinity/releases/Java-Thread-Affinity-3.26ea5), [BOM-2.26ea26](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.26ea26)
