### ISSUE TITLE
NullPointerException in LockCheck.getProcessForCpu()

### ISSUE THREAD

**Issue by dsmonkey** [OpenHFT/Java-Thread-Affinity#62]
We recently got an NPE with multiple threads in multiple processes executing AffinityLock.aquireLock() on the same machine. We specify the CPUs each process can use so they don't conflict.

java.lang.NullPointerException
at net.openhft.affinity.LockCheck.getProcessForCpu(LockCheck.java:120)
at net.openhft.affinity.LockCheck.isCpuFree(LockCheck.java:67)
at net.openhft.affinity.AffinityLock.canReserve(AffinityLock.java:253)
at net.openhft.affinity.LockInventory.acquireLock(LockInventory.java:90)
at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:184)
at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:167)
at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:145)

Another process on the same machine had a different error at the same time but this one seems to be ok because the cpu was eventually assigned
java.io.FileNotFoundException: /tmp/cpu-16.lock (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at net.openhft.affinity.LockCheck.getProcessForCpu(LockCheck.java:118)
at net.openhft.affinity.LockCheck.isCpuFree(LockCheck.java:67)
at net.openhft.affinity.AffinityLock.canReserve(AffinityLock.java:253)
at net.openhft.affinity.LockInventory.acquireLock(LockInventory.java:90)
at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:184)
at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:167)
at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:145)
...
net.openhft.affinity.AffinityLock INFO: Assigning cpu 16 to {<thread_name>}

We haven't seen this NPE before and we've been running this code for a while. We're using version 3.1.1. Any ideas?

**Comment by dsmonkey** [comment]
I see the the latest version updates LockCheck.isCpuFree() to catch RuntimeException, so this may not be an issue any more
