### ISSUE TITLE
Exception in thread "Processor-MT" java.lang.NoClassDefFoundError: net/openhft/affinity/AffinityLock Occurred in Docker Image

### ISSUE THREAD

**Issue by Umartahir93** [OpenHFT/Java-Thread-Affinity#69]
I am trying to run this library in docker image, but getting the following exception
```

**Exception in thread "Processor-MT" java.lang.NoClassDefFoundError: net/openhft/affinity/AffinityLock
        at SI.Processor.run(Processor.java:6650)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: net.openhft.affinity.AffinityLock
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 2 more
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/app/lib/jaxb-impl-2.3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.**
```

I am not sure why this error is occurring if I run my project in my host machine aka without creating images it gets to run smoothly. Problem is only arising in docker images.

**Comment by vemv** [comment]
Hi, I'm not a contributor to this repo but I think it helps pointing out that this issue lacks sufficient information:

* How to reproduce?
  * e.g., what is a minimal Dockerfile with your attempt?

`java.lang.NoClassDefFoundError: net/openhft/affinity/AffinityLock` looks like a pretty vanilla error to me - are you experienced setting up Maven dependencies in a docker-based setup?

If not, you could try various templates - often CI providers guide you in setting up a Java project. [Example](https://circleci.com/docs/2.0/language-java/)

Hope it helps!

**Comment by JerryShea** [comment]
Closing as no response from @Umartahir93
